"""Add system account to ledger entries

Revision ID: c8d17b626a85
Revises: 906c99438174
Create Date: 2026-08-17 10:29:32.536143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d17b626a85'
down_revision = '906c99438174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.String(length=20), nullable=False))
        batch_op.alter_column('wallet_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.alter_column('wallet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('account_type')

    # ### end Alembic commands ###
